export const STOP_FETCH_PIECHART_DATA = "STOP_FETCH_PIECHART_DATA"
export const START_FETCH_PIECHART_DATA = "START_FETCH_PIECHART_DATA"
export const SET_PIECHART_DATA = "SET_PIECHART_DATA"

export const STOP_FETCH_BARCHART_DATA = "STOP_FETCH_BARCHART_DATA"
export const START_FETCH_BARCHART_DATA = "START_FETCH_BARCHART_DATA"

export const STOP_FETCH_HEATCHART_DATA = "STOP_FETCH_HEATCHART_DATA"
export const START_FETCH_HEATCHART_DATA = "START_FETCH_HEATCHART_DATA"

export const STOP_FETCH_LINECHART_DATA = "STOP_FETCH_LINECHART_DATA"
export const START_FETCH_LINECHART_DATA = "START_FETCH_LINECHART_DATA"

export const SET_DATE = "SET_DATE"

export const STOP_FETCH_DEVICELIST_DATA = "STOP_FETCH_DEVICELIST_DATA"
export const START_FETCH_DEVICELIST_DATA = "START_FETCH_DEVICELIST_DATA"
