export const FETCH_PIECHART_DATA = "FETCH_PIECHART_DATA"
export const STOP_FETCH_PIECHART_DATA = "STOP_FETCH_PIECHART_DATA"
export const START_FETCH_PIECHART_DATA = "START_FETCH_PIECHART_DATA"

export const FETCH_BARCHART_DATA = "FETCH_BARCHART_DATA"
export const STOP_FETCH_BARCHART_DATA = "STOP_FETCH_BARCHART_DATA"
export const START_FETCH_BARCHART_DATA = "START_FETCH_BARCHART_DATA"